[package]
name = "helix-website"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
helix-database = {workspace = true}
helix-common = {workspace = true}
helix-utils = {workspace = true}
helix-housekeeper = {workspace = true}
helix-beacon-client = {workspace = true}
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ethereum-consensus = { workspace = true }
deadpool-postgres = { workspace = true }
url = { workspace = true }
async-trait = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }

askama = "0.12"
alloy-primitives = "0.7.7"
num-format = "0.4.4"
